---
namespace: 'sbaerlocher'
name: 'windows'
version: 0.0.8
readme: README.md
authors:
  - 'Simon Baerlocher (https://sbaerlocher.ch)'
description: 'Ansible Collection for Windows functions.'
license:
  - MIT
tags:
  - windows
dependencies: {}
repository: 'https://www.github.com/sbaerlocher/ansible.windows'
documentation: 'https://sbaerlocher.github.io/ansible.windows'
homepage: 'https://sbaerlocher.ch/projects/ansible.windows'
issues: 'https://www.github.com/sbaerlocher/ansible.windows/issues'
